### ISSUE TITLE
Cancellation policy disallows Sandstorm Inc from keeping offline backups

### ISSUE THREAD

**Issue by lablua** [sandstorm-io/tos-pp#13]
[The text](https://github.com/sandstorm-io/tos-pp/blame/master/tos.md#L82) under the heading "Cancellation, the bullet "Once the current pay period ends, all of your data will be deleted." does not permit Sandstorm Development Group, Inc. to maintain offline backups of any user data. If there is a cancellation at the end of the last day of the current pay period, it's unlikely any offline backups could be removed immediately.

Also, this might not be a good way to treat user data - allowing a little grace period in case they realize they didn't copy all their data out before cancelling would be nicer for the user in most cases. (Particularly if the user's poor security practices lead to loss of control of their account and it is cancelled by someone with unauthorized access.)

**Comment by kentonv** [comment]
Yeah, good call.
