### ISSUE TITLE
"anyone who might be interested" -> something more specific

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/tos-pp#4]
> In the case of harassment, if in our judgment the case warrants it (such as if you make explicit death threats towards an individual), we may reveal your identity to **anyone who might be interested**, such as to the harassed parties or to your mother.

Perhaps we should more specifically enumerate, say:
- The harassed parties.
- Law enforcement.
- Your mother.

(Via @ocdtrekkie, who says we should definitely keep "your mother" in there.)

**Comment by ocdtrekkie** [comment]
+1
