### ISSUE TITLE
Disallow violating other services' terms of service via Sandstorm

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/tos-pp#5]
We could explicitly state that using Sandstorm to connect to some other service in a way that violates their Terms of Service may lead to us revealing your identity to that other service.

But there is a concern that some people have ridiculous ToS. Thoughts?

(via @ocdtrekkie)

**Comment by ocdtrekkie** [comment]
@kentonv While I would contest Sandstorm.io having vague terms that allow sharing of our identity information, I think it's fair for Sandstorm.io to have vague terms to disallow sharing of our identity information.

So, if your grain is reported for violating another service's Terms of Service, I think the terminology you use above, _may lead us to_ is probably fair. You're not committing to reveal our identity to a third party service if they claim their ToS is violated, you're saying you may. Presumably if you feel that their ToS is not stupid, and the request is not pedantic or trivial.
